scaler_X: StandardScaler
scaler_Y: StandardScaler
transforms_Y:
- logit
- log
- logit_2y-1
separate_targets: False
model: LGBMRegressor
param_grid:
  n_estimators: [100, 150]
  num_leaves: [100, 400, 800]
  learning_rate: [0.05, 0.1]
  reg_lambda: [0, 0.01]
  min_child_weight: [0.001, 1, 3, 5]
  subsample: [0.8, 1.0]
  colsample_bytree: [0.8, 1.0]
  random_state: [1126]
  n_jobs: [16]
fit_param_grid:
  sample_weight: [uniform]
params_formatter: ne_{n_estimators}_nl_{num_leaves}_lr_{learning_rate}_ld_{reg_lambda}_mcw_{min_child_weight}_subs_{subsample}_cstree_{colsample_bytree}_sw_{sample_weight}
