scaler_X: StandardScaler
scaler_Y: StandardScaler
transforms_Y:
- logit
- log
- logit_2y-1
separate_targets: True
model: Ridge
param_grid:
  alpha: [0.00001, 0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000]
  fit_intercept: [False]
  random_state: [1126]
fit_param_grid:
  sample_weight: [uniform, target_reciprocal]
params_formatter: alpha_{alpha}_sw_{sample_weight}
