scaler_X: StandardScaler
scaler_Y: StandardScaler
transforms_Y:
- logit
- log
- logit_2y-1
separate_targets: False
model: RandomForestRegressor
param_grid:
  n_estimators: [20, 50, 100]
  max_depth: [5, 10, 20, 30]
  random_state: [1126]
  n_jobs: [8]
  criterion: [mae]
params_formatter: ne_{n_estimators}_md_{max_depth}
