scaler_X: StandardScaler
scaler_Y: StandardScaler
transforms_Y:
- logit
- log
- logit_2y-1
model: Lasso
param_grid:
  alpha: [0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000]
  max_iter: [2000]
  tol: [0.00001]
  fit_intercept: [False]
  random_state: [1126]
separate_targets: True
params_formatter: alpha_{alpha}
